# Generated by Django 5.2.16 on 2026-07-19 18:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('registration_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('vin_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(db_index=True, max_length=50)),
                ('manufacturing_year', models.IntegerField()),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('insurance_number', models.CharField(blank=True, max_length=100)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('rc_expiry', models.DateField(blank=True, null=True)),
                ('fuel_type', models.CharField(db_index=True, max_length=50)),
                ('mileage', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('current_odometer', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('capacity', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_USE', 'In Use'), ('MAINTENANCE', 'Under Maintenance'), ('INACTIVE', 'Inactive')], db_index=True, default='AVAILABLE', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='drivers/')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(max_length=30)),
                ('license_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('license_expiry', models.DateField(db_index=True)),
                ('joining_date', models.DateField()),
                ('experience', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('address', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(max_length=100)),
                ('blood_group', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_vehicle', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_driver', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
