# Generated by Django 5.2.16 on 2026-07-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='FleetGuard Logistics', max_length=150)),
                ('company_email', models.EmailField(default='info@fleetguard.com', max_length=254)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('theme', models.CharField(default='dark', max_length=20)),
                ('fuel_unit', models.CharField(default='Liters', max_length=20)),
                ('distance_unit', models.CharField(default='Kilometers', max_length=20)),
                ('notification_email', models.BooleanField(default=True)),
                ('notification_sms', models.BooleanField(default=True)),
            ],
        ),
    ]
